#!/usr/bin/env bash

system_type=$(uname -s)


# ---------------------------------------------------------------------------
# OS X Darwin / Macbook Pro
# ---------------------------------------------------------------------------
#
if [ "$system_type" = "Darwin" ]; then

  if ! command -v brew >/dev/null 2>&1; then
    echo "--- Installing homebrew ..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "--- Updating homebrew bundle ..."
    brew bundle --global
  fi


  ~/.bootstrap/darwin/aws-mfa.sh
fi

# ---------------------------------------------------------------------------
# Linux / Fedora
# ---------------------------------------------------------------------------
#
if [ "$system_type" = "Linux" ]; then

  distro=$(grep -Po "(?<=^NAME=).*" /etc/os-release |  tr '[:upper:]' '[:lower:]')
  if [ "$distro" = '"fedora linux"' ]; then
    sudo ~/.bootstrap/fedora/system-packages.sh
    sudo ~/.bootstrap/fedora/rpmfusion.sh
    sudo dnf update -y

    sudo ~/.bootstrap/fedora/vscode.sh
    ~/.bootstrap/generic/vscode-install-extensions.sh

    sudo ~/.bootstrap/fedora/virtualbox.sh


    if [ ! -f /etc/yum.repos.d/kubernetes.repo ]; then
      sudo cp ~/.bootstrap/fedora/kubernetes.repo /etc/yum.repos.d/kubernetes.repo
    fi
    sudo ~/.bootstrap/fedora/minikube.sh
  fi

fi

~/.bootstrap/generic/bashit.sh
~/.bootstrap/generic/vim.sh
