# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10


[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 25
style = "bold red"

[directory]
truncation_length = 8
truncation_symbol = "…/"

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true
